// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASlhOZSgPizveEneO32aPtmZiORGAh0BU',
    appId: '1:578249993917:web:1009de96e025bd09f511d4',
    messagingSenderId: '578249993917',
    projectId: 'horoscopo-12apo',
    authDomain: 'horoscopo-12apo.firebaseapp.com',
    storageBucket: 'horoscopo-12apo.appspot.com',
    measurementId: 'G-PD54T3CCHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJKpGuwwVnxPcoJFpnFhqz6K76pOEPbi8',
    appId: '1:578249993917:android:95229ee91627686ef511d4',
    messagingSenderId: '578249993917',
    projectId: 'horoscopo-12apo',
    storageBucket: 'horoscopo-12apo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl6T3Uf8P72wjV7IDWWgT_IVUTYTvFBYA',
    appId: '1:578249993917:ios:9ca901982c16c934f511d4',
    messagingSenderId: '578249993917',
    projectId: 'horoscopo-12apo',
    storageBucket: 'horoscopo-12apo.appspot.com',
    iosBundleId: 'click.al2.horoscopo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl6T3Uf8P72wjV7IDWWgT_IVUTYTvFBYA',
    appId: '1:578249993917:ios:5200f926fad8f05df511d4',
    messagingSenderId: '578249993917',
    projectId: 'horoscopo-12apo',
    storageBucket: 'horoscopo-12apo.appspot.com',
    iosBundleId: 'click.al2.horoscopo.RunnerTests',
  );
}
